print('Twinkle twinkle little star '
      '\n\tHow i wonder what you are \n\t\tUp above te world so high,'
      ' \n\t\t\tLike a diamond in the sky. '
      '\n\nWhen the blazing sun is gun'
      '\n\tWhen he nothing sign upon '
      '\n\t\t Then you show your little light '
      '\n\t\t\t Twinkle twinkle through the night '
      '\n\nThen the traveller in the dark,'
      ' \n\tThanks you for your tiny spark, \n\t\tHe could not see where to go '
      '\n\t\t\t If you din not twinkle so. \n\nIn the dark blue sky you keep, '
      '\n\tAnd often through my curtains beep, \n\t\tFor you never shut your eyes \n\t\t\t'
      'Till the sun is in the sky. \n\nAs your bright and tiny spark, '
      '\n\tLight the the traveller in the dark, \n\t\tThough i know'
      ' not what you are,'
      ' \n\t\t\tTwinkle twinkle star.')